### PR TITLE
Enabled CORS and time fix

### PR DESCRIPTION
**Pull request by dburugupalli**
1. Addition of CORS header so that communication between and fronted react application and python flask web server is enabled. 

2. Minor bug fix to the /list_projects for the past one hour, considered all the edge case scenarios. 

3. Removal of extra spaces in config.sh 

How to star the web server.

```bash
. config.sh
python3 app.py
```

### CODE REVIEW

**Comment by dburugupalli** [comment]
#6  This pull request resolves this issue.

**Comment by dburugupalli** [comment]
PR to address issue #6

**Comment by shakyav** [comment]
@gagansk @dburugupalli 
PR review done , working fine
image

Fetching data from the backend , in this PR the data that being generated doesn't have Activation time field, hence we can't see that in front end, but otherwise it is working as expected.

**Comment by dburugupalli** [comment]
@shakyav This PR contains Cross Resource Origin Sharing Enabling and Some of the edge cases to list_projects_in last one hour.

**Comment by gagansk** [comment]
Approving since it was tested by @shakyav

**Pull request merged**
